spring.application.name=dieti-estates
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=didonato.andrea.info@gmail.com
spring.mail.password=btcp lwjt pkbo atji
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true